### ISSUE TITLE
Homepage Structure

### ISSUE THREAD

**Issue by ievaza** [front-end-by-rimantas/18-grupe-portfolio-saas-one#1]
Home page section (HTML div's and CSS files): 
- [x] HEADER
- [x] HERO
- [x] HOMEPAGE ABOUT
- [x] FEATURE
- [x] APP
- [x] PROJECTS
- [x] FAQ
- [x] TESTIMONALS
- [x] OUR TEAM
- [x] ADDRESS
- [x] FOOTER

**Comment by rositatisor** [comment]
Reikia sutvarkyti/sudėti link'us:
    ```<!-- reset -->
    <link rel="stylesheet" href="./css/reset.css">
    <link rel="stylesheet" href="./css/layout.css">
    <!-- 3rd party -->
    <!-- components -->
    <!-- custom -->
    <link rel="stylesheet" href="./css/custom.css">```
