### ISSUE TITLE
Multi-pages: Our team

### ISSUE THREAD

**Issue by rositatisor** [front-end-by-rimantas/18-grupe-portfolio-saas-one#46]
- [x] Our team section in following multi-pages:
- About
- Our team

**Comment by georgioupanayiotis** [comment]
Hello @rositatisor can you assign me this ?

**Comment by rositatisor** [comment]
Hello, dear @georgioupanayiotis,
unfortunately I am not able to assign you any tasks of this project as it is our group work, which will determine our final results from this module.
Sorry for any inconvenience caused.
